---

- name: Install icinga2 basic packages
  apt:
    name: gnupg
    state: present

- name: Add icinga2 repo key
  apt_key:
    url: "{{ icingaweb2_apt_repo.gpgkey }}"
    state: present
  when: icingaweb2_apt_repo.gpgkey is defined
        and icingaweb2_manage_repo_icinga

- name: Add icinga2 repository
  apt_repository:
    repo: "{{ icingaweb2_apt_repo.repo }}"
    state: present
    update_cache: yes
  when: icingaweb2_manage_repo_icinga

- name: Install icingaweb2 basic packages
  apt:
    name: "{{ item }}"
    state: "{{ icingaweb2_state }}"
  register: track_icingaweb2_install
  with_items:
    - git
    - icingaweb2
    - icingacli
